# Generated by Django 4.2.6 on 2023-10-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
