# Generated by Django 4.2.6 on 2023-10-30 18:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboardApi', '0002_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('cnpj', models.TextField(max_length=14, unique=True)),
                ('cep', models.TextField(max_length=8)),
            ],
            options={
                'verbose_name': 'empresa',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id_produto_cliente', models.CharField(max_length=200)),
                ('id_sku', models.CharField(max_length=100)),
                ('ean', models.CharField(max_length=14)),
                ('descricao', models.CharField(max_length=150)),
                ('produto_ou_servico', models.CharField(choices=[('PR', 'Produto'), ('SR', 'Servico')], default='PR', max_length=2)),
                ('vl_compra', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_custo', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_venda', models.DecimalField(decimal_places=4, max_digits=13)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardApi.empresa')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('id_venda_cliente', models.TextField(max_length=200)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_expedicao', models.DateTimeField(blank=True, null=True)),
                ('data_faturamento', models.DateTimeField(blank=True, null=True)),
                ('vl_bruto_servico', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_bruto_produto', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_bruto', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_desconto_servico', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_desconto_produto', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_desconto', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_liquido', models.DecimalField(decimal_places=4, max_digits=13)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardApi.empresa')),
            ],
            options={
                'db_table': 'venda',
            },
        ),
        migrations.CreateModel(
            name='VendaItem',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_unitario', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_bruto', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_desconto', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_liquido', models.DecimalField(decimal_places=4, max_digits=13)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboardApi.produto')),
                ('id_venda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboardApi.venda')),
            ],
            options={
                'db_table': 'venda_item',
            },
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('id_empresa', 'id_produto_cliente'), name='Unique Produto vs Empresa'),
        ),
    ]
