# Generated by Django 4.2.6 on 2023-10-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='id_empresa',
            new_name='empresa',
        ),
    ]
