# Generated by Django 4.2.6 on 2023-10-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0006_remove_produto_unique_produto_vs_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nomeFantasia',
            field=models.CharField(default='', max_length=150, verbose_name='nome_fantasia'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razaoSocial',
            field=models.CharField(default='', max_length=150, verbose_name='razao_social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
