# Generated by Django 4.2.6 on 2023-10-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0007_empresa_nomefantasia_empresa_razaosocial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='nomeFantasia',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='razaoSocial',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(default='', max_length=150),
        ),
    ]
