# Generated by Django 4.2.6 on 2023-10-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0008_remove_empresa_nomefantasia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo_cliente',
            field=models.CharField(default='', max_length=50),
        ),
    ]
