# Generated by Django 4.2.6 on 2023-11-03 19:49

import dashboardApi.models.validators.cnpj_cpf_validator.cnpj_cpf_validator
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0009_empresa_codigo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'cidade',
            },
        ),
        migrations.CreateModel(
            name='InscricaoEstadual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inscricao_estadual', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'inscricao_estadual',
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('codigo_origem', models.TextField(max_length=200)),
                ('descricao_operacao', models.CharField(max_length=50)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_expedicao', models.DateTimeField(blank=True, null=True)),
                ('data_faturamento', models.DateTimeField(blank=True, null=True)),
                ('vl_bruto_servico', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_bruto_produto', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_bruto', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_desconto_servico', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_desconto_produto', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_desconto', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_liquido', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_base_icms', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_icms', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_base_substituicao_tributaria', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_substituicao_tributaria', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_ipi', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_cofins', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_pis', models.DecimalField(decimal_places=4, max_digits=13)),
            ],
            options={
                'db_table': 'operacao',
            },
        ),
        migrations.CreateModel(
            name='OperacaoItem',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_unitario', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_bruto', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_desconto', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_liquido', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_base_icms', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_icms', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_base_substituicao_tributaria', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_substituicao_tributaria', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_ipi', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_cofins', models.DecimalField(decimal_places=4, max_digits=13)),
                ('vl_pis', models.DecimalField(decimal_places=4, max_digits=13)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboardApi.operacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboardApi.produto')),
            ],
            options={
                'db_table': 'operacao_item',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('codigo_cliente', models.CharField(db_index=True, max_length=50)),
                ('nome', models.CharField(help_text='Pode ser o primeiro nome da pessoa física ou razão social', max_length=150)),
                ('sobrenome', models.CharField(help_text='sobrenome da pessoa física', max_length=150)),
                ('nome_fantasia', models.CharField(help_text='Nome fantasia da empresa ou apelido da pessoa física', max_length=150)),
            ],
            options={
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='PessoaEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('codigo_origem', models.CharField(max_length=60)),
                ('cep', models.CharField(help_text='Deve inserir apenas os números do CEP, sem espaços e caracteres especiais.', max_length=8)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=60)),
                ('celular', models.CharField(blank=True, max_length=15)),
                ('telefone1', models.CharField(blank=True, max_length=15)),
                ('telefone2', models.CharField(blank=True, max_length=15)),
                ('identificador_endereco', models.CharField(choices=[('FIXO', 'Fixo'), ('COBRANCA', 'Cobranca'), ('OUTRO', 'Outro')], default='FIXO', help_text='O endereço pode ser identificado com as seguintes TAGS: FIXO, COBRANCA, OUTRO', max_length=20)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboardApi.cidade')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardApi.pessoa')),
            ],
            options={
                'db_table': 'pessoa_endereco',
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[dashboardApi.models.validators.cnpj_cpf_validator.cnpj_cpf_validator.cpf_validator])),
                ('data_nascimento', models.DateField(null=True)),
                ('registro_geral_numero', models.CharField(max_length=50)),
                ('registro_geral_sigla_emissor', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'pessoa_fisica',
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[dashboardApi.models.validators.cnpj_cpf_validator.cnpj_cpf_validator.cnpj_validator])),
                ('data_criacao', models.DateField(null=True)),
            ],
            options={
                'db_table': 'pessoa_juridica',
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardApi.pais', unique=True)),
            ],
            options={
                'db_table': 'uf',
            },
        ),
        migrations.RemoveField(
            model_name='vendaitem',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='vendaitem',
            name='venda',
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
        migrations.DeleteModel(
            name='VendaItem',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pessoa_fisica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboardApi.pessoafisica'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pessoa_juridica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboardApi.pessoajuridica'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardApi.pessoa'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardApi.empresa'),
        ),
        migrations.AddField(
            model_name='inscricaoestadual',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboardApi.pessoaendereco'),
        ),
        migrations.AddField(
            model_name='inscricaoestadual',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardApi.pessoa'),
        ),
        migrations.AddField(
            model_name='inscricaoestadual',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboardApi.uf'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboardApi.uf'),
        ),
        migrations.AddConstraint(
            model_name='cidade',
            constraint=models.UniqueConstraint(fields=('uf', 'nome'), name='Cidade já cadastrada para a UF informada.'),
        ),
    ]
