# Generated by Django 4.2.6 on 2023-11-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApi', '0010_cidade_inscricaoestadual_operacao_operacaoitem_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uf',
            name='estado',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='uf',
            name='sigla',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='uf',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboardApi.pais', unique=True),
        ),
    ]
